"""版本信息 — 每次发版更新这里"""

VERSION = "1.1.0"
VERSION_DATE = "2026-04-26"

CHANGELOG = {
    "1.1.0": {
        "date": "2026-04-26",
        "changes": [
            "🚨 紧急稳定性更新 — 适配 HOI4 1.18 (Case Green)",
            "崩溃修复: continent.txt 自动写 vanilla 7 大陆 (修 portraits 除零崩溃)",
            "崩溃修复: division names 改 for_countries={ } (default=yes 是非法字段)",
            "崩溃修复: state ID 自动压实 1..N 连续 (修 Missing State ID)",
            "崩溃修复: character 文件 UTF-8 BOM + name 用 ID (不再写中文导致 GBK 编码崩)",
            "崩溃修复: history/countries 文件名 = {TAG}.txt (PHYSFS 严格匹配)",
            "崩溃修复: REPLACE_PATHS 加 common/on_actions (vanilla 引用已删 decisions 触发 access violation)",
            "崩溃修复: 战略区域不连通自动拆分",
            "性能: 战略区域生成快 13× (590 次连通分量 → 48 次)",
            "新功能: 🗑 删除 State / Country UI (含二次确认 + Ctrl+Z 撤销)",
            "新功能: 📐 从地形反推高度图 (用距离场算法, mountain 山尖到 240)",
            "新功能: 国家边框高亮 (默认所有国家白边, 选中红边)",
            "新功能: 地形底图源切换 (高度图 / 省份地形属性) - View 菜单",
            "新功能: provincial_terrain 拖拽分配 (按住鼠标拖过批量改)",
            "新功能: terrain 笔刷长按持续画 (按住不动也画)",
            "新功能: coal 资源 (vanilla 1.18 完整 7 种战略资源)",
            "防呆: 9 个破坏性操作加二次确认弹窗 (auto_terrain/auto_height/downgrade/import/new_land/smooth_coast/density_clear/default_map_reset/continent_remove)",
            "解耦: 改 terrain 视觉不再自动改 provincial_terrain (省份属性是用户精挑细选的)",
            "美化: 海洋距离场渐变 (近海青绿 → 远海深蓝)",
            "美化: 陆地高度调亮 + 雪山 (>200 渐变白) + 海岸沙滩 (4px 浅黄)",
            "美化: terrain 颜色饱和度提升",
            "i18n: yml 文件名加 zz_ 前缀确保覆盖 vanilla state 翻译",
            "i18n: yml 写入支持中文 (去掉 isascii 限制)",
        ],
    },
    "1.0.0": {
        "date": "2026-04-18",
        "changes": [
            "1.0 正式版发布",
            "全面国际化：所有 UI 文字支持中英文实时切换",
            "语言切换不再需要重启，立即生效",
            "修复 New Project 对话框 OK 按钮不渲染问题",
        ],
    },
    "1.0.2-beta": {
        "date": "2026-04-16",
        "changes": [
            "重大崩溃修复：rivers.bmp 非法索引5/8+对角线像素（EXCEPTION_INT_DIVIDE_BY_ZERO）",
            "重大崩溃修复：coastal province 缺 naval_base_spawn（tile_map 不一致时补救）",
            "重大崩溃修复：heightmap 算法改为距离场（海岸渐变，不再悬崖切下去）",
            "重大崩溃修复：smart_auto_terrain 结合 heightmap 防延伸到海",
            "重大崩溃修复：compute_provincial_terrain_from_bmp 只处理真陆地 province",
            "新增：独立「地形（属性）」显示模式（gameplay 地形，和视觉分离）",
            "新增：自动生成地形同步 provincial_terrain dict（视觉→属性单向同步）",
            "新增：未分配省份红色高亮 + 状态栏提示",
            "新增：批量建州选中省份黄色高亮",
            "新增：后勤铁路/补给点可视化 overlay",
            "新增：山脉画线实时红线反馈",
            "UI：字体/配色可读性优化（_DIM 对比度 3.5→4.9，字号 +1px）",
            "UI：最近项目列表 360→640，加 tooltip",
            "UI：高度/地形/河流 tab 顶部都加一键生成大按钮",
            "UI：模式导航加风险等级标签（🎨视觉/🟢基础/🟠影响游戏/🔴崩溃高发）",
            "UI：河流 tab 改版（3步引导）+ 切过去自动 1px",
            "UI：属性地形 tab 默认查看模式，开「分配模式」才改",
            "修复：RIVER_WIDTH_TYPES 去掉非法索引 5/8（用户手动选会崩）",
        ],
    },
    "1.0.1-beta": {
        "date": "2026-04-15",
        "changes": [
            "UI 重构：13模式合并为7个图标导航 + 子标签页",
            "画笔改为圆形笔刷（密度/陆地/地形/河流统一）",
            "海岸线平滑支持框选局部区域",
            "面板 Section 标题加粗加大",
            "模式提示条自适应高度 + 允许换行",
        ],
    },
    "1.0.1": {
        "date": "2026-04-14",
        "changes": [
            "智能高度图生成（海岸距离场+Perlin噪声山脉）",
            "智能地形生成（高度分层+噪声边界+散点斑点）",
            "地形圆形画笔（1-200px+软边缘）",
            "法线贴图修复（游戏内可见地形起伏）",
            "导出崩溃修复（decisions/raids categories保留vanilla）",
            "高度/地形模式顺序调整（先高度后地形）",
            "高度页面重写（使用说明+种子+山脉强度）",
            "工具面板恢复分组折叠+整体滚动",
        ],
    },
    "1.0.0-beta.1": {
        "date": "2026-04-14",
        "changes": [
            "导出速度从10+分钟优化到5秒",
            "修复coastal no port崩溃（可正常进入游戏）",
            "新增导出预检对话框（自动补全缺失数据）",
            "新增导出范围选择（地图/States/国家等可单独勾选）",
            "新增增量生成功能（选区域重新生成省份）",
            "修复导入MOD地图崩溃",
            "修复cities.bmp尺寸错误",
            "修复高度图海岸线凹陷",
            "新增wiki知识库（docs/wiki/）",
            "CLAUDE.md全面重写",
        ],
    },
}
